# 不可修改，仅通过配置文件生效
Actor:
    ArmL: "Hand"        # "Hand" | "Grip"
    ArmR: "Hand"
    OffsetL:        # 抓取点相对于手腕坐标系的偏移
        Position:   # 单位 m
            - 0.0     # x
            - 0.0     # y
            - 0.0     # z
        Eular:      # 弧度 rx->ry->rz 外旋
            - 0.0     # rx
            - 0.0     # ry
            - 0.0     # rz   
    OffsetR:
        Position:  
            - 0.0   
            - 0.0    
            - 0.0    
        Eular:      
            - 0.0     
            - 0.0     
            - 0.0    

Address:
    ArmL: "192.168.101.6:18080"    # "192.168.1.18:8080"
    ArmR: "192.168.101.6:28080"    # "192.168.2.18:8080"
    # 仅配置 Actor 为 Hand 时启用
    HandL: "192.168.101.6:16000"   # "192.168.12.210:6000" | "485"
    HandR: "192.168.101.6:26000"   # "192.168.11.210:6000" | "485"
    # server
    Server: "127.0.0.1:5000"
# 可修改
Speed: 10 